repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-case-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
    args: ['--fix=no']

- repo: local
  hooks:
  - id: fmt
    name: fmt
    language: system
    files: '\.rs$'
    entry: cargo fmt -- --check
    pass_filenames: false
  - id: clippy
    name: clippy
    language: system
    files: '\.rs$'
    entry: cargo clippy --all-targets --all -- -Dwarnings
    pass_filenames: false
