[package]
name = "rating-exchange-bot"
version = "0.3.3"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
anyhow = "1.0.100"
thiserror = "2.0.17"
async-trait = "0.1.89"
dotenvy = "0.15.7"
envy = "0.4.2"

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }

time = "0.3.46"
regex = "1.12.2"
lazy-regex = "3.4.2"
deunicode = "1.6.2"
strum = { version = "0.27.1", features = ["derive"] }
bimap = "0.6.3"

tokio = { version = "1.48.0", features = ["rt-multi-thread", "signal"] }

sqlx = { version = "0.8.6", features = [
    "runtime-tokio-native-tls",
    "sqlite",
    "migrate",
    "time",
    "macros",
] }

serenity = { version = "0.12.5", default-features = false, features = [
    "client",
    "gateway",
    "model",
    "native_tls_backend",
    "cache",
] }
poise = "0.6.1"

indoc = "2.0.7"

[dev-dependencies]
test-log = { version = "0.2.19", default-features = false, features = [
    "trace",
] }
map-macro = "0.3.0"

[profile.dev.package.sqlx-macros]
opt-level = 3
