[package]
name = "rating-exchange-bot"
version = "0.3.3"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.99"
thiserror = "2.0.12"
async-trait = "0.1.88"
dotenvy = "0.15.7"
envy = "0.4.2"

tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }

time = "0.3.43"
regex = "1.11.1"
lazy-regex = "3.4.1"
deunicode = "1.6.2"
strum = { version = "0.27.1", features = ["derive"] }
bimap = "0.6.3"

tokio = { version = "1.47.1", features = ["rt-multi-thread", "signal"] }

sqlx = { version = "0.8.6", features = [
    "runtime-tokio-native-tls",
    "sqlite",
    "migrate",
    "time",
    "macros",
] }

serenity = { version = "0.12.4", default-features = false, features = [
    "client",
    "gateway",
    "model",
    "native_tls_backend",
    "cache",
] }
poise = "0.6.1"

indoc = "2.0.6"

[dev-dependencies]
test-log = { version = "0.2.17", default-features = false, features = [
    "trace",
] }
map-macro = "0.3.0"

[profile.dev.package.sqlx-macros]
opt-level = 3
