[package]
name = "rating-exchange-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
pretty_env_logger = "0.4.0"
map-macro = "0.2.5"

[dev-dependencies]
env_logger = "0.10.0"
test-log = "0.2.11"
