name: Build & Publish Docker Image

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Apply Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Check flake
        uses: DeterminateSystems/flake-checker-action@v9

      - name: Build container image
        run: nix build .#container

      - name: Push container image to GHCR
        run: skopeo copy docker-archive:result docker://ghcr.io/${{ vars.DOCKER_IMAGE_NAME }}:latest --additional-tag ${{ steps.meta.outputs.tags }}
