name: Build & Publish Docker Image

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Build the container
        run: nix build .#container

      - name: Upload the container image to GHCR
        run: skopeo copy docker-archive:result docker://ghcr.io/${{ vars.DOCKER_IMAGE_NAME }}:latest --additional-tag ${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }} 
