name: Run Tests

on:
  push:
  workflow_dispatch:

env:
  DATABASE_URL: "sqlite://rebot.sqlite3?mode=rwc"
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install sqlx-cli
        run: |
          SQLX_CLI_VERSION="$(sed -rn 's/^sqlx = \{ version = "([0-9.]+)".*$/\1/p' Cargo.toml)"
          echo "Required sqlx-cli version: $SQLX_CLI_VERSION"
          cargo install sqlx-cli --force --version "$SQLX_CLI_VERSION" --no-default-features --features sqlite

      - name: Set Up the Database
        run: sqlx database setup

      - name: Build
        run: cargo build --profile dev

      - name: Test
        run: cargo test --profile dev
